### PR TITLE
Update wasmedge

### PR DESCRIPTION
**Pull request by phil-opp**
Update wasmedge to latest version to fix CI.

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

The reviewers provided three individual summaries for the pull request titled "Update wasmedge". Overall, the reviewers warn about potential issues and errors that may arise from the upgrade and recommend an in-depth review before merging. Specifically, the lack of information about the chosen versions of the crates can cause compatibility issues, which might impact the project. The change in the use of `with_func_single_thread` to `with_func` introduces performance improvements to the code but may also cause potential thread safety issues if the code is not thread-safe. Finally, the code changes do not appear to introduce obvious problems but compatibility issues may arise with the upgraded version of Wasmedge, and a security review is recommended before merging the pull request.

## Details

### [Commit caaa1adc7d287ea5374a4a34d6103310e095a16a](https://github.com/WasmEdge/WasmEdge/pull/15/commits/caaa1adc7d287ea5374a4a34d6103310e095a16a)
The patch updates the version of several crates, including `bindgen`, `num-derive`, `proc-macro2`, `syn`, `unicode-ident`, `wasmedge-macro`, `wasmedge-sdk`, `wasmedge-sys`, and `wasmedge-types`. The update changes are expected to contain bug fixes, feature enhancements, or potential security improvements to the crates.

However, there is no clear explanation of why these specific versions were chosen, and the potential impact on the project is unknown. Furthermore, there might be compatibility issues with the current dependencies of the project, but this information is not included in the patch. It would be best to review the pull request thoroughly and consider the implications on the project before merging it.

### [Commit c64792c00a79ffbc34e0dbbe84c7c9a4abaa2333](https://github.com/WasmEdge/WasmEdge/pull/15/commits/c64792c00a79ffbc34e0dbbe84c7c9a4abaa2333)
The patch changes the use of `with_func_single_thread` to `with_func` in the `wasmedge` module of the `function-executor` crate. This is likely to improve the performance of the code by allowing the functions to be executed on multiple threads. However, there may be potential problems if the code is not thread-safe. But without further information about the code, it is difficult to make an informed judgement about the potential problems.

### [Commit ec75fd4beb491cf3a90223ae4ca68ab3fbadc568](https://github.com/WasmEdge/WasmEdge/pull/15/commits/ec75fd4beb491cf3a90223ae4ca68ab3fbadc568)
This patch updates wasmedge, refactors code, and removes some dependencies that are not used. The key changes include upgrading wasmedge to version 0.8.1, modifying dependencies in the Cargo.toml file, and switching from Executor, Store, and ImportObject types to Vm, ConfigBuilder and ImportObjectBuilder. 

There are no obvious potential problems with the code changes, but it may be a good idea to check that the upgraded wasmedge version is fully compatible with the existing code. Cybersecurity vulnerabilities might also appear with any update, so a security review of Wasmedge is recommended.

**Comment by phil-opp** [comment]
@EmisonLu Do you have an idea how to fix the remaining compile issues? I'm currently a bit stuck because `build_as_wasi` no longer exists. It was removed in https://github.com/WasmEdge/WasmEdge/pull/2301 but I don't see any replacement in there. I haven't found anything related in the WasmEdge changelogs either.

The reason that I'm trying to do this update is because the CI script always installs the latest WasmEdge version, which no longer works with the older library versions.

**Comment by EmisonLu** [comment]
@apepkuss Hi, sorry to bother you! Do you know how to solve this problem?

**Comment by apepkuss** [comment]
@phil-opp I created a new PR (#16) for fixing the CI issues here. The changes in #16 are made based on the `update-wasmedge` branch. Thanks a lot!

**Comment by phil-opp** [comment]
Thanks a lot for the quick fixes!

**Pull request merged**
